Grupo14Discapacitados/Grupo14Discapacitados/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.estadisticos.urls')),
    path('', include('aplicaciones.login.urls')),
]

Grupo14Discapacitados/aplicaciones/estadisticos/urls.py
from django.urls import path
from . import views
import aplicaciones.estadisticos.views 
app_name='estadisticos_app'
urlpatterns = [
    path('estadisticos/prueba/',views.prueba,name='prueba'),
    path('estadisticos/listar-empresas/',views.ListarEmpresa.as_view(),name='listar-empresas'),
    path('estadisticos/crear-empresa/',views.CrearEmpresa.as_view(),name='crear-empresa'),
    path('estadisticos/listar-discapacidad/',views.ListarDiscapacidad.as_view(),name='listar-discapacidad'),
    path('estadisticos/crear-discapacidad/',views.CrearDiscapacidad.as_view(),name='crear-discapacidad'),
    path('estadisticos/eliminar-discapacidad/<pk>/',views.EliminarDiscapacidad.as_view(),name='eliminar-discapacidad'),
    path('estadisticos/modificar-discapacidad/<pk>/',views.ModificarDiscapacidad.as_view(),name='modificar-discapacidad'),
    path('estadisticos/generales',views.estadisticas,name="estadisticas generales"),
    path('estadisticos/getcenso/<id>',views.getCenso,name="estadisticas generales"),
    path('estadisticos/vergrafica/<id>',views.verGrafica,name="estadisticas individuales"),
    path('estadisticos/getgenerales',views.getGenerales,name="estadisticas generales"),
]

Grupo14Discapacitados/aplicaciones/estadisticos/models.py
from django.db import models

# Create your models here.
class Censo(models.Model):
    idcenso=models.BigAutoField(primary_key=True)
    nombre_censo=models.CharField(max_length=255)
    discapacidad=models.CharField(max_length=255,default="")
    isGeneral=models.BooleanField(default=False)
    fecha = models.DateField()
    descripcion=models.CharField(max_length=1000,default=" ")
    activo=models.BooleanField('Activo')
    def __str__(self):
        return self.nombre_censo


class Zona(models.Model):
    idzona=models.BigAutoField(primary_key=True)
    censo=models.ForeignKey(Censo,on_delete=models.CASCADE)
    cantmujeres=models.IntegerField()
    cantHombres=models.IntegerField()
    localidad=models.ForeignKey('Localidad',on_delete=models.CASCADE)
    

class Localidad(models.Model):
    idlocalidad=models.BigAutoField(primary_key=True)
    nombre=models.CharField(max_length=50)
    isUrbano=models.BooleanField()
    tipo=models.ForeignKey('TipoLocalidad',on_delete=models.CASCADE)


class TipoLocalidad(models.Model):
    idtipo=models.BigAutoField(primary_key=True)
    nombre=models.CharField(max_length=50)



class Discapacidad(models.Model):
    id_discapacidad=models.BigAutoField(primary_key=True)
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    )
    sexo=models.CharField( GENDER_CHOICES,max_length=13,default='')
    LOCALIZACION_CHOICES = (
        ('U', 'Urbana'),
        ('R', 'Rural'),
    )
    DISCAPACIDAD_CHOICES1 = (
        ('Visual', 'Discapacidad Visual'),
        ('Fisica', 'Discapacidad Fisica'),
        ('Comunicacion', 'Discapacidad de Comunicacion'),
        ('Auditiva', 'Discapacidad Auditiva'),
        ('intelectual', 'Discapacidad intelectual'),
        ('social', 'Discapacidad Psicosocial o Mental'),
        ('Dependencia', 'Discapacidad por Dependencia'),
    )
    DISCAPACIDAD_CHOICES = (
        ('Visual', 'Discapacidad Visual'),
        ('Fisica', 'Discapacidad Fisica'),
        ('Comunicacion', 'Discapacidad de Comunicacion'),
        ('Auditiva', 'Discapacidad Auditiva'),
        ('intelectual', 'Discapacidad intelectual'),
        ('social', 'Discapacidad Psicosocial o Mental'),
        ('Dependencia', 'Discapacidad por Dependencia'),
    )
    localizacion=models.CharField( LOCALIZACION_CHOICES,max_length=13,default='')
    tipo_discapacidad=models.CharField( DISCAPACIDAD_CHOICES1,max_length=13,default='')
    total_personas = models.PositiveIntegerField()
    censo = models.ForeignKey(Censo, on_delete=models.RESTRICT, related_name='discapacidades_censo')
    def __str__(self):
        return self.nombre_discapacidad
     
class Empresa(models.Model):
    idempresa=models.BigAutoField(primary_key=True)
    nombre_empresa = models.CharField(max_length=255)
    GENDER_CHOICES = (
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
    )
    sexo=models.CharField( GENDER_CHOICES,max_length=13,default='')
    LOCALIZACION_CHOICES = (
        ('Urbana', 'Urbana'),
        ('Rural', 'Rural'),
    )
    DISCAPACIDAD_CHOICES = (
        ('Visual', 'Discapacidad Visual'),
        ('Fisica', 'Discapacidad Fisica'),
        ('Comunicacion', 'Discapacidad de Comunicacion'),
        ('Auditiva', 'Discapacidad Auditiva'),
        ('intelectual', 'Discapacidad intelectual'),
        ('social', 'Discapacidad Psicosocial o Mental'),
        ('Dependencia', 'Discapacidad por Dependencia'),
    )
    localizacion=models.CharField( LOCALIZACION_CHOICES,max_length=13,default='')
    tipo_discapacidad=models.CharField( DISCAPACIDAD_CHOICES,max_length=13,default='')
    total_personas = models.PositiveIntegerField()
    censo = models.ForeignKey(Censo, on_delete=models.RESTRICT, related_name='empresa_censo')
    
    def __str__(self):
        return self.nombre_empresa
    

Grupo14Discapacitados/aplicaciones/estadisticos/forms.py
from django import forms
from django.forms import ModelForm
from .models import Empresa,Discapacidad
from django.core.exceptions import ValidationError

        
GENDER_CHOICES = (
    ('Masculino ', 'Masculino'),
    ('Femenino', 'Femenino'),
    
)
LOCALIZACION_CHOICES = (
        ('Urbano', 'Urbana'),
        ('Rural', 'Rural'),
    )
DISCAPACIDAD_CHOICES1 = (
        ('Visual', 'Discapacidad Visual'),
        ('Fisica', 'Discapacidad Fisica'),
        ('Comunicacion', 'Discapacidad de Comunicacion'),
        ('Auditiva', 'Discapacidad Auditiva'),
        ('intelectual', 'Discapacidad intelectual'),
        ('social', 'Discapacidad Psicosocial o Mental'),
        ('Dependencia', 'Discapacidad por Dependencia'),
    )
class DiscapacidadForm(forms.ModelForm):
    sexo = forms.ChoiceField(choices=GENDER_CHOICES, label="Sexo")
    localizacion = forms.ChoiceField(choices=LOCALIZACION_CHOICES, label="Localizacion")
    tipo_discapacidad = forms.ChoiceField(choices=DISCAPACIDAD_CHOICES1, label="Discapacidad")
    class Meta:
        model = Discapacidad
        fields = ['tipo_discapacidad','sexo','localizacion','total_personas','censo']
    

class EmpresaForm(ModelForm):
    
    sexo = forms.ChoiceField(choices=GENDER_CHOICES, label="Sexo")
    localizacion = forms.ChoiceField(choices=LOCALIZACION_CHOICES, label="Localizacion")
    tipo_discapacidad = forms.ChoiceField(choices=DISCAPACIDAD_CHOICES1, label="Discapacidad")
    class Meta:
        model = Empresa
        fields = ['nombre_empresa','sexo','localizacion','tipo_discapacidad','total_personas','censo']

    

Grupo14Discapacitados/aplicaciones/estadisticos/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from .models import Censo, Empresa,Discapacidad, Localidad, Zona
from django.urls import reverse_lazy
from .forms import EmpresaForm,DiscapacidadForm
from django.contrib import messages
from django.core.serializers import serialize 


# Create your views here.
def prueba(request):
    return render(request,'estadisticos/prueba.html')

class ListarDiscapacidad(ListView):
    template_name='estadisticos/listar-discapacidad.html'
    model=Discapacidad
    context_object_name='lista_discapacitado'
    queryset=Discapacidad.objects.all()
    
class CrearDiscapacidad(CreateView):
    template_name='estadisticos/crear-discapacidad.html'
    form_class=DiscapacidadForm
    success_url=reverse_lazy('estadisticos_app:listar-discapacidad')
    def form_valid(self, form):
        messages.success(self.request, 'La discapacidad se ha agregado exitosamente')
        return super().form_valid(form)
    
class EliminarDiscapacidad(DeleteView):
    template_name='estadisticos/eliminar-discapacidad.html'
    model=Discapacidad
    success_url=reverse_lazy('estadisticos_app:listar-discapacidad')
    def delete(self, request,*args, **kwargs):
        messages.success(request,'Discapacidad eliminada con exito')
        return super().delete(request,*args,**kwargs)
    
class ModificarDiscapacidad(UpdateView):
    template_name='estadisticos/modificar-discapacidad.html'
    model=Discapacidad
    form_class=DiscapacidadForm
    success_url=reverse_lazy('estadisticos_app:listar-discapacidad')
    def form_valid(self, form):
        messages.success(self.request, 'La discapacidad se ha modificado exitosamente')
        return super().form_valid(form)

class ListarEmpresa(ListView):
    template_name='estadisticos/listar-empresas.html'
    model=Empresa
    context_object_name='lista_empresas'
    queryset=Empresa.objects.all()
    
class CrearEmpresa(CreateView):
    template_name='estadisticos/crear-empresa.html'
    form_class=EmpresaForm
    success_url=reverse_lazy('estadisticos_app:listar-empresas')
    def form_valid(self, form):
        messages.success(self.request, 'La empresa se ha agregado exitosamente')
        return super().form_valid(form)
    

def estadisticas(request):
    contexto={}
    return render(request,"estadisticos/generales.html",contexto)

def getCenso(request,id):
    data= list()
    data.append(serialize('json',Censo.objects.filter(idcenso=id)))
    data.append(serialize('json',Zona.objects.filter(censo=id)))
    i=0 
    localidad={}
    for local in Zona.objects.filter(censo=id):
        print(local.localidad.nombre)
        localidad[local.localidad.idlocalidad]=local.localidad.nombre
    data.append(json.dumps(localidad))
    return JsonResponse(data,safe=False)

def verGrafica(request,id):

    contexto={}
    data=Censo.objects.filter(idcenso=id).first()
    contexto['censo']=data 

    return render(request,'estadisticos/vergraficos.html',contexto)

def getGenerales(request):
    data= list()
    data.append(serialize('json',Censo.objects.filter(isGeneral=True)))
    for cen in Censo.objects.filter(isGeneral=True) :
        data.append(serialize('json',Zona.objects.filter(censo=cen)))
        localidad={}
        for local in Zona.objects.filter(censo=cen) :
            print(local.localidad.nombre)
            localidad[local.localidad.idlocalidad]=local.localidad.nombre
        data.append(json.dumps(localidad))
    return JsonResponse(data,safe=False)

Grupo14Discapacitados/templates/estadisticos/crear-discapacidad.html
<!DOCTYPE html>
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <title>Document</title>
    
</head>
<body>
    
    <div class="container">
        <div class="row justify-content-center mt-5">
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header">
                <h3 class="mb-0">Agregar Discapacidad</h3>
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="{{ form.localizacion.id_for_label }}">Discapacidad:</label>
                    {{ form.tipo_discapacidad |attr:"class:form-control" | attr:"class:custom-select" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.sexo.id_for_label }}">Sexo:</label>
                    {{ form.sexo |attr:"class:form-control" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.localizacion.id_for_label }}">Localizacion:</label>
                    {{ form.localizacion |attr:"class:form-control" | attr:"class:custom-select" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.total_personas.id_for_label }}">Total Personas:</label>
                    {{ form.total_personas |attr:"class:form-control" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.censo.id_for_label }}">Censo:</label>
                    {{ form.censo |attr:"class:form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Agregar</button>
                  <a href="{% url 'estadisticos_app:listar-discapacidad' %}" class="btn btn-secondary">Cancelar</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
</body>
</html>

Grupo14Discapacitados/templates/estadisticos/crear-empresa.html
<!DOCTYPE html>
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <title>Document</title>
    
</head>
<body>
    
    <div class="container">
        <div class="row justify-content-center mt-5">
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header">
                <h3 class="mb-0">Agregar Empresa</h3>
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-outline">
                    <label for="{{ form.nombre_discapacidad.id_for_label }}">Nombre Empresa:</label>
                    {{ form.nombre_empresa| attr:"class=form-control form-control-lg" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.sexo.id_for_label }}">Sexo:</label>
                    {{ form.sexo |attr:"class:form-control" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.localizacion.id_for_label }}">Localizacion:</label>
                    {{ form.localizacion |attr:"class:form-control" | attr:"class:custom-select" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.localizacion.id_for_label }}">Discapacidad:</label>
                    {{ form.tipo_discapacidad |attr:"class:form-control" | attr:"class:custom-select" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.total_personas.id_for_label }}">Total Personas:</label>
                    {{ form.total_personas |attr:"class:form-control" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.censo.id_for_label }}">Censo:</label>
                    {{ form.censo |attr:"class:form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Agregar</button>
                  <a href="{% url 'estadisticos_app:listar-empresas' %}" class="btn btn-secondary">Cancelar</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
</body>

Grupo14Discapacitados/templates/estadisticos/eliminar-discapacidad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <title>Eliminar Discapacidad</title>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header">
                <div class="container">
                    <div class="row">
                    <div class="col-sm-12">
                        <h2>Eliminar Discapacidad</h2>
                        <form method="post">
                        {% csrf_token %}
                        <p>Desea eliminar la discapacidad seleccionada?</p>
                        <button type="submit" class="btn btn-danger">Si</button>
                        <a href="{% url 'estadisticos_app:listar-discapacidad' %}" class="btn btn-secondary">Cancelar</a>
                        </form>
                        
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Grupo14Discapacitados/templates/estadisticos/generales.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estadisticas Generales</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    <div class="container">
      <div class="row">
        <h1 class="display-6">estadisticas generales</h1>
      </div>
      <div class="row" id="grafica">
       
      </div>
    </div>
    <script src="{% static 'js/chartjs/chart.umd.js' %}"></script>
    <Script>
      const options = {
                method: 'GET',
                mode: 'no-cors',
                credentials: 'omit',
                redirect: 'follow',
            };
      let contenedor = document.getElementById('grafica');
      fetch('http://127.0.0.1:8000/estadisticos/getgenerales', options)
                .then(response => response.json())
                .then(data => {
                  let censo = JSON.parse(data[0]);
                  console.log(censo);
                })
                .catch(err => console.error(err));
    </Script>
</body>
</html>

Grupo14Discapacitados/templates/estadisticos/listar-discapacidad.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Lista de Discapacidad</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
   <style>
      .btn {
         margin-right: 10px;
      }
   </style>
</head>
<body>
   {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    <script>
      setTimeout(function() {
          document.querySelector('.alert').classList.add('d-none');
      }, 5000);
  </script>
{% endif %}
   <div class="container">
      <h1>Lista Discapacidad</h1>
      <div class="container mt-3">
        <div class="row mb-3">
           <div class="col-12 text-right">
              <a href="{% url 'estadisticos_app:crear-discapacidad' %}" class="btn btn-primary">Agregar Discapacidad</a>
           </div>
        </div>
      <table class="table">
         <thead>
            <tr>
               <th>Discapacidad</th>
               <th>Sexo</th>
               <th>Zona</th>
               <th>Total Personas</th>
               <th>Accion</th>
            </tr>
         </thead>
         <tbody>
			{% for d in lista_discapacitado  %}
				<tr>
				   <td>{{ d.tipo_discapacidad }}</td>
                    <td>{{ d.sexo }}</td>
                    <td>{{ d.localizacion}}</td>
                    <td>{{ d.total_personas}}</td>
				   <td>
					  <a href="{% url 'estadisticos_app:modificar-discapacidad' d.id_discapacidad %}" class="btn btn-primary btn-sm">Editar</a>
					  <a href="{% url 'estadisticos_app:eliminar-discapacidad' d.id_discapacidad %}" class="btn btn-danger btn-sm">Eliminar</a>
				   </td>
				</tr>
			{% endfor %} 
         </tbody>
      </table>
   </div>
</body>
</html>

Grupo14Discapacitados/templates/estadisticos/listar-empresas.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Lista de Empresas</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
   <style>
      .btn {
         margin-right: 10px;
      }
   </style>
</head>
<body>
   {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    <script>
      setTimeout(function() {
          document.querySelector('.alert').classList.add('d-none');
      }, 5000);
  </script>
{% endif %}
   <div class="container">
      <h1>Lista Empresas</h1>
      <div class="container mt-3">
        <div class="row mb-3">
           <div class="col-12 text-right">
              <a href="{% url 'estadisticos_app:crear-empresa'%}" class="btn btn-primary">Agregar Empresa</a>
           </div>
        </div>
      <table class="table">
         <thead>
            <tr>
               
               <th>Nombre</th>
               <th>Sexo</th>
               <th>Localizacion</th>
               <th>Discapacidad</th>
               <th>Total Personas</th>
               <th>Censo</th>
               <th>Acciones</th>
            </tr>
         </thead>
         <tbody>
			{% for e in lista_empresas  %}
				<tr>
				   
                    <td>{{ e.nombre_empresa }}</td>
                    <td>{{ e.sexo}}</td>
                    <td>{{ e.localizacion }}</td>
                    <td>{{ e.tipo_discapacidad }}</td>
                    <td>{{ e.total_personas }}</td>
                    <td>{{ e.censo }}</td>
				   <td>
					  <a href="#" class="btn btn-primary btn-sm">Editar</a>
					  <a href="#" class="btn btn-danger btn-sm">Eliminar</a>
				   </td>
				</tr>
			{% endfor %} 
         </tbody>
      </table>
   </div>
</body>
</html>

Grupo14Discapacitados/templates/estadisticos/modificar-discapacidad.html
<!DOCTYPE html>
{% load widget_tweaks %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <title>Document</title>
    
</head>
<body>
    
    <div class="container">
        <div class="row justify-content-center mt-5">
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header">
                <h3 class="mb-0">Agregar Discapacidad</h3>
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="{{ form.localizacion.id_for_label }}">Discapacidad:</label>
                    {{ form.tipo_discapacidad |attr:"class:form-control" | attr:"class:custom-select" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.sexo.id_for_label }}">Sexo:</label>
                    {{ form.sexo |attr:"class:form-control" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.localizacion.id_for_label }}">Localizacion:</label>
                    {{ form.localizacion |attr:"class:form-control" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.total_personas.id_for_label }}">Total Personas:</label>
                    {{ form.total_personas |attr:"class:form-control" }}
                  </div>
                  <div class="form-group">
                    <label for="{{ form.censo.id_for_label }}">Censo:</label>
                    {{ form.censo |attr:"class:form-control" }}
                  </div>
                  <input type="submit" class="btn btn-primary" value="Actualizar">
                  <a href="{% url 'estadisticos_app:listar-discapacidad' %}" class="btn btn-secondary">Cancelar</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
</body>
</html>

Grupo14Discapacitados/templates/estadisticos/prueba.html
<!DOCTYPE html>
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>PRUEBA</h1>
</body>
</html>

Grupo14Discapacitados/templates/estadisticos/vergraficos.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estadisticas-</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body ></body>>
    <div class="container-md">

        <div class="row">
            {% if censo %}
            <input type="number" hidden value="{{censo.idcenso}}" id="ncenso">
            <h6 class="display-6">Nombre: {{censo.nombre_censo}}</h6>
            <h6 class="display-6">Discapacidad:{{censo.discapacidad}}</h6>
            <h6 class="display-6">Fecha:{{censo.fecha}}</h6>
            <h6 class="display-6">Descripcion:{{censo.descripcion}}</h6>
            {% endif %}

        </div>
        <div class="row">
            <h1 class="display-4">Cantidad vs Localidad</h1>
            <div style="width: 800px;"><canvas id="grafica1"></canvas></div>
        </div>
        
        <div class="row">
            <div class="col">
                <h1 class="display-6">Cantidad vs Localidad # Mujeres</h1>
                <div style="width: 600px;"><canvas id="grafica3"></canvas></div>
            </div>
            <div class="col">
                <h1 class="display-6">Cantidad vs Localidad # Hombres </h1>
                <div style="width: 600px;"><canvas id="grafica4"></canvas></div>

            </div>
        </div>


    </div>
    <script src="{% static 'js/chartjs/chart.umd.js' %}"></script>
    <script>
        let ncenso = document.getElementById('ncenso').value;
        const options = {
            method: 'GET',
            mode: 'no-cors',
            credentials: 'omit',
            redirect: 'follow',
        };

        fetch('http://127.0.0.1:8000/estadisticos/getcenso/' + ncenso, options)
            .then(response => response.json())
            .then(data => {
                const datamap = [];
                let obtenido = JSON.parse(data[1]);
                for (let i = 0; i < obtenido.length; i++) {
                    let datos = obtenido[i].fields;
                    datamap.push(datos);
                }
                console.log(datamap);
                const localidades = JSON.parse(data[2]);
                console.log(localidades);
                (async function () {
                    new Chart(
                        document.getElementById('grafica1'),
                        {
                            type: 'bar',
                            data: {
                                labels: datamap.map(row =>  localidades[row.localidad]),                          
                                
                                datasets: [
                                    {
                                        label: 'Cantidad de Personas',
                                        data: datamap.map(row => row.cantmujeres + row.cantHombres)
                                    }
                                ]
                            }
                        }
                    );
                })();

                (async function () {
                    new Chart(
                        document.getElementById('grafica3'),
                        {
                            type: 'bar',
                            data: {
                                labels: datamap.map(row =>  localidades[row.localidad]),
                                datasets: [
                                    {
                                        label: 'Cantidad de Personas',
                                        data: datamap.map(row => row.cantmujeres )
                                    }
                                ]
                            }
                        }
                    );
                })();

                (async function () {
                    new Chart(
                        document.getElementById('grafica4'),
                        {
                            type: 'bar',
                            data: {
                                labels: datamap.map(row =>  localidades[row.localidad]),
                                datasets: [
                                    {
                                        label: 'Cantidad de Personas',
                                        data: datamap.map(row => row.cantHombres)
                                    }
                                ]
                            }
                        }
                    );
                })();
            })
            .catch(err => console.error(err));

    </script>
</body>

</html>